# Generated by Django 4.2.5 on 2023-09-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LIQUID', 'Liquid'), ('SOLIDE', 'Solide'), ('MAGIC', 'Magic'), ('AEROSOL', 'Aerosol')], max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DROPS', 'Drops'), ('TINCTURE', 'Tincture'), ('INFUSION', 'Infusion'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('EMULSION', 'Emulsion'), ('CAPSULE', 'Capsule'), ('TABLET', 'Tablet'), ('POWDER', 'Powder'), ('GRANULE', 'Granule'), ('DRAGEE', 'Dragee'), ('CARAMEL', 'Caramel'), ('PENCIL', 'Pencil'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Get'), ('SUPPOSITORS', 'Supppositors'), ('PASTE', 'Paste')], max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('medicine_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicineform', verbose_name='Medicine form')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contraindication', models.ManyToManyField(blank=True, null=True, to='pharmacy.contraindication', verbose_name='Contrandications')),
                ('disease', models.ManyToManyField(to='pharmacy.disease', verbose_name='Diseases')),
                ('medicine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinetype', verbose_name='Medicine type')),
            ],
        ),
    ]
