# Generated by Django 4.2.5 on 2023-09-29 18:34

from django.db import migrations


def add_medicine_forms(apps, schema_editor):
    medicine_form_model = apps.get_model("pharmacy", "MedicineForm")
    medicine_form_model.objects.bulk_create(
        medicine_form_model(name=name) for name in ("LIQUID", "SOLIDE", "MAGIC", "AEROSOL")
    )


def add_medicine_types(apps, schema_editor):
    medicine_type_model = apps.get_model("pharmacy", "MedicineType")
    medicine_form_model = apps.get_model("pharmacy", "MedicineForm")

    liquid = medicine_form_model.objects.get(name="LIQUID")
    medicine_type_model.objects.bulk_create(
        medicine_type_model(name=name, medicine_form=liquid)
        for name in ("DROPS", "TINCTURE", "INFUSION", "SYRUP", "SUSPENSION", "EMULSION")
    )

    solid = medicine_form_model.objects.get(name="SOLIDE")
    medicine_type_model.objects.bulk_create(
        medicine_type_model(name=name, medicine_form=solid)
        for name in ("CAPSULE", "TABLET", "POWDER", "GRANULE", "DRAGEE", "CARAMEL", "PENCIL")
    )

    magic = medicine_form_model.objects.get(name="MAGIC")
    medicine_type_model.objects.bulk_create(
        medicine_type_model(name=name, medicine_form=magic)
        for name in ("CREAM", "OINTMENT", "GEL", "SUPPOSITORS", "PASTE")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_medicine_forms),
        migrations.RunPython(add_medicine_types),
    ]

